# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csm < Formula
  desc "TUI for browsing and resuming Claude Code sessions"
  homepage "https://github.com/ninanung/csm"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ninanung/csm/releases/download/v0.3.2/csm_0.3.2_darwin_amd64.tar.gz"
      sha256 "0a74e72616dcb09a2e93183a8465d6006abc715a3798efc3c53d331564ad95e4"

      define_method(:install) do
        bin.install "csm"
        generate_completions_from_executable(bin/"csm", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ninanung/csm/releases/download/v0.3.2/csm_0.3.2_darwin_arm64.tar.gz"
      sha256 "f71ba1c2b332539a98bf4e729d09443f97c5d8c354f49218fef0e2d28e45e737"

      define_method(:install) do
        bin.install "csm"
        generate_completions_from_executable(bin/"csm", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ninanung/csm/releases/download/v0.3.2/csm_0.3.2_linux_amd64.tar.gz"
      sha256 "8b435e92cad29257568bbda9115a2add8fe4e5f083f89df42e2ffd031a2cfc09"
      define_method(:install) do
        bin.install "csm"
        generate_completions_from_executable(bin/"csm", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ninanung/csm/releases/download/v0.3.2/csm_0.3.2_linux_arm64.tar.gz"
      sha256 "7e2e307c6944252d8f3c799ad7fcea3b5fef404c33946ff55873faadae4eaec0"
      define_method(:install) do
        bin.install "csm"
        generate_completions_from_executable(bin/"csm", "completion")
      end
    end
  end

  test do
    assert_match "csm", shell_output("#{bin}/csm version")
  end
end
