# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csm < Formula
  desc "TUI for browsing and resuming Claude Code sessions"
  homepage "https://github.com/ninanung/csm"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ninanung/csm/releases/download/v0.3.1/csm_0.3.1_darwin_amd64.tar.gz"
      sha256 "9eedaff51137fa059f0b94514ea73aca1dd436e232be0fd231998650354d4df8"

      define_method(:install) do
        bin.install "csm"
        generate_completions_from_executable(bin/"csm", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ninanung/csm/releases/download/v0.3.1/csm_0.3.1_darwin_arm64.tar.gz"
      sha256 "fcdc0890115b46b85933ca71ff7f1dc008a7d20545d6a70af0f20b7d7fae10c5"

      define_method(:install) do
        bin.install "csm"
        generate_completions_from_executable(bin/"csm", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ninanung/csm/releases/download/v0.3.1/csm_0.3.1_linux_amd64.tar.gz"
      sha256 "5012d1d13ff71495cbdf34719b06d13d9313e317f7cbed618f136d3577aa4a81"
      define_method(:install) do
        bin.install "csm"
        generate_completions_from_executable(bin/"csm", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ninanung/csm/releases/download/v0.3.1/csm_0.3.1_linux_arm64.tar.gz"
      sha256 "549659ed252fb94321ee8d066d6c19478414ad4e9f13cb51636e5a1078911dce"
      define_method(:install) do
        bin.install "csm"
        generate_completions_from_executable(bin/"csm", "completion")
      end
    end
  end

  test do
    assert_match "csm", shell_output("#{bin}/csm version")
  end
end
